server:
  port: 80
cors:
  originPatterns: http://localhost:8080,http://localhost:3000,https://www.erudio.com.br
file:
  upload-dir: /workspace/udemy/SpringBoot2025-AWS-GCP-Docker/Code/UploadDir
security:
  jwt:
    token:
      secret-key: 53cr37
      expire-lenght: 3600000
email:
  subject: "Default Subject"
  message: "Default Message"
spring:
  application:
    name: rest-with-spring-boot-and-java-erudio
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${JDBC_URL} # Esta sendo passado nas variaveis de ambiente do run configuration
    username: root
    password: rds02061625
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
    show-sql: false
    open-in-view: false
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${EMAIL_USERNAME}
    password: ${EMAIL_PASSWORD}
    properties:
      mail.debug: true
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
      mail.smtp.starttls.required: true
      mail.smtp.ssl.trust: smtp.gmail.com
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 200MB
      max-request-size: 215 MB
logging:
  level:
    # root: WARN
    br.com.erudio: DEBUG
spring-doc:
  paths-to-match:
    - /auth/**
    - /api/**/v1/**
  swagger-ui:
    use-root-path: true